seed_everything: 0

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.01

model:
  class_path: SMPTempModel
  init_args:
    encoder_name: resnet18
    encoder_weights: imagenet
    n_channels: 40
    flatten_temporal_dimension: false
    # Placeholder. train.py overwrites this per fold from the training years.
    pos_class_weight: 236.0
    loss_function: Focal

do_train: true
do_test: true
do_predict: false
